### ISSUE TITLE
Add support to generate domain models for updating resource types in specific product blocks

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-core#186]
The generate domain model can update/rename resource types over all product block, but we would also want to update resource types within a single product block.

### Tasks
- [x] change the `updates` argument to accept `block_resource_types` to update resource types per product block. 
       `updates = { 'block_resource_types': { 'block_name': { 'old_rt': 'new_rt' } } }`
- [X] ~~create a function to get the resources to update within product blocks with interactive shell. (could be split into a new issue).~~ moved to separate issue to build interactive shell
- [x] filter out the specific updates from the model diffs.
- [x] create a function to generate sql to update resource types within product blocks.
