### ISSUE TITLE
[Maintenance]: Add the ability to unit test with celery executor

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-core#273]
# Description

It would be great if we can test the application with celery as executor, so we can be sure it works corretly and can prevent issues like #271 

Now when setting the `EXECUTOR=celery` in your `.env`, tests break with `Celery has not been initialised yet` error.

# Tasks

- [ ] Add new celery tests to `test/celery_tests`
- [ ] Make use of `pytest-celery` to startup/configure a Celery worker
- [ ] Testcases:
  - [ ] Starting a workflow
  - [ ] Resuming a workflow
- [ ] Add a CI workflow in .github/workflows, using the same services as the other CI workflows (postgres/redis)

**Comment by Mark90** [comment]
The recently released `pytest-celery` plugin is probably useful here

https://github.com/celery/pytest-celery/releases/tag/v1.0.0
https://docs.celeryq.dev/projects/pytest-celery/en/latest/getting-started/first-steps.html

**Comment by saket-geant** [comment]
https://github.com/workfloworchestrator/orchestrator-core/pull/1023
